---

# ansible-playbook -b -i 192.168.0.X, -k -u osmc main.yml

- hosts: all

  roles:
    - role: geerlingguy.docker
      vars:
        docker_apt_ansible_distribution: "{{ ansible_os_family }}"
        docker_install_compose_plugin: no
        docker_packages:
          - docker-{{ docker_edition }}:arm64
          - docker-{{ docker_edition }}-cli:arm64
          - containerd.io:arm64
        docker_users:
          - osmc

  tasks:
    - ansible.builtin.apt:
        name:
          - hd-idle
          - rsync

    - ansible.builtin.cron:
        name: docker refresh
        job: /home/osmc/.docker/refresh.sh
        minute: "0"
        hour: "3"
        user: osmc

    - ansible.builtin.file:
        path: /home/osmc/.docker
        state: directory
        owner: osmc
        group: osmc

    - ansible.builtin.copy:
        content: |
          #!/bin/bash
          docker image pull -q sharevb/it-tools:latest && docker image pull -q linuxserver/wireguard:latest || exit
          docker container stop it-tools wireguard
          docker container rm it-tools wireguard
          docker container run -d --name it-tools -p 8080:8080 --restart always sharevb/it-tools:latest
          docker container run -d --name wireguard --cap-add NET_ADMIN -e PUID=$(id -u) -e PGID=$(id -g) -e TZ=Europe/Stockholm -e SERVERURL=localhost -e PEERS=1 -e LOG_CONFS=false -p 51820:51820/udp --restart always -v /home/osmc/.docker/wireguard:/config linuxserver/wireguard:latest
          docker image prune -f
        dest: /home/osmc/.docker/refresh.sh
        mode: "555"
        owner: osmc
        group: osmc

    - ansible.builtin.lineinfile:
        path: "{{ item.path }}"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
        backrefs: "{{ item.backrefs | default(omit) }}"
      loop:
        - path: /boot/config-user.txt
          regexp: ^#?arm_freq=
          line: arm_freq=2000
        - path: /boot/config-user.txt
          regexp: ^#?gpu_freq=
          line: gpu_freq=750
        - path: /boot/config-user.txt
          regexp: ^#?over_voltage=
          line: over_voltage=6
        - path: /etc/default/hd-idle
          regexp: ^#?HD_IDLE_OPTS=
          line: HD_IDLE_OPTS="-i 0 -a /dev/sda -i 600 -l /var/log/hd-idle.log"
        - path: /home/osmc/.bashrc
          regexp: ^#?alias ll=(.*)
          line: alias ll=\1
          backrefs: yes
        - path: /home/osmc/.bashrc
          regexp: ^#?export LC_ALL=
          line: export LC_ALL=C.UTF-8

    - ansible.builtin.replace:
        path: "{{ item.path }}"
        regexp: "{{ item.regexp }}"
        replace: "{{ item.replace }}"
      loop:
        - path: /etc/ld.so.preload
          regexp: '^(\/usr\/lib\/libarmmem\.so)$'
          replace: '#\1'
        - path: /home/osmc/.bash_logout
          regexp: '^(\s*)(\[\s+-x\s+\/usr\/bin\/clear_console\s.*)$'
          replace: '\1: # \2'

    - ansible.builtin.raw: echo -e "{{ ansible_password }}\n{{ new_password }}\n{{ new_password }}" | passwd
      become_user: osmc
      when: new_password != ansible_password

  vars_prompt:
    - name: new_password
      prompt: NEW password
      confirm: yes
