---

- ansible.builtin.get_url:
    url: https://repository.mullvad.net/deb/mullvad-keyring.asc
    dest: /usr/share/keyrings/mullvad-keyring.asc
  become: yes

- ansible.builtin.apt_repository:
    repo: deb [signed-by=/usr/share/keyrings/mullvad-keyring.asc arch=amd64] https://repository.mullvad.net/deb/stable stable main
    filename: mullvad
  become: yes

- ansible.builtin.deb822_repository:
    architectures: amd64
    components: stable
    name: docker
    signed_by: https://download.docker.com/linux/ubuntu/gpg
    suites: "{{ lookup('ansible.builtin.ini', 'UBUNTU_CODENAME', file='/etc/os-release', type='properties') }}"
    uris: https://download.docker.com/linux/ubuntu
  become: yes

- ansible.builtin.apt:
    name: "{{ item.name | default(omit) }}"
    update_cache: "{{ item.update_cache | default(omit) }}"
  become: yes
  loop:
    - update_cache: yes
    - name:
        - containerd.io
        - docker-buildx-plugin
        - docker-ce
        - docker-ce-cli
        - docker-compose-plugin
        - ffmpeg
        - git
        - mullvad-vpn
        - vim
        - wireguard

- ansible.builtin.shell:
    cmd: "{{ item.cmd | default(['curl', '--create-dirs', '--location', '--output', item.file, item.url | default(omit), '&&', 'chmod', '+x', item.file] | join(' ')) }}"
    creates: "{{ item.file }}"
  become: "{{ item.become | default(omit) }}"
  loop:
    - url: https://gist.githubusercontent.com/luudvig/160c757005be61102bac4e3128ab313e/raw/encrypt-symmetric.sh
      file: "{{ ansible_facts.env.HOME }}/.local/bin/encrypt-symmetric.sh"
    - url: https://gist.githubusercontent.com/luudvig/10d227c86139029e73f4fdfc763d768e/raw/two-pass.sh
      file: "{{ ansible_facts.env.HOME }}/.local/bin/two-pass.sh"
    - cmd: curl --location --output-dir /tmp --remote-name https://github.com/denoland/deno/releases/latest/download/deno-x86_64-unknown-linux-gnu.zip && unzip -d {{ ansible_facts.env.HOME }}/.local/bin /tmp/deno-x86_64-unknown-linux-gnu.zip deno
      file: "{{ ansible_facts.env.HOME }}/.local/bin/deno"
    - url: https://svtplay-dl.se/download/latest/svtplay-dl
      file: "{{ ansible_facts.env.HOME }}/.local/bin/svtplay-dl"
    - url: https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp
      file: "{{ ansible_facts.env.HOME }}/.local/bin/yt-dlp"
    - cmd: curl --location https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-4 | bash
      file: /usr/local/bin/helm
      become: yes
    - url: https://dl.k8s.io/release/{{ lookup('ansible.builtin.url', 'https://dl.k8s.io/release/stable.txt') }}/bin/linux/amd64/kubectl
      file: /usr/local/bin/kubectl
      become: yes
    - url: https://github.com/kubernetes/minikube/releases/latest/download/minikube-linux-amd64
      file: /usr/local/bin/minikube
      become: yes

- ansible.builtin.user:
    name: "{{ ansible_facts.user_id }}"
    append: yes
    groups: docker
  become: yes

- community.general.flatpak:
    name:
      - com.spotify.Client
      - org.gimp.GIMP
