---

- ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ ansible_facts.env.HOME }}/.config/containers/systemd"
    - "{{ ansible_facts.env.HOME }}/Transmission/config"
    - "{{ ansible_facts.env.HOME }}/Transmission/downloads"

- ansible.builtin.copy:
    content: "{{ item.content | default(omit) }}"
    src: "{{ item.src | default(omit) }}"
    dest: "{{ item.dest }}"
    mode: "{{ item.mode | default(omit) }}"
    force: "{{ item.force | default(omit) }}"
  become: "{{ item.become | default(omit) }}"
  loop:
    - content: |
        [Container]
        Environment=TZ=Europe/Stockholm
        Image=docker.io/linuxserver/transmission:latest
        PublishPort=127.0.0.1:9091:9091
        UserNS=keep-id:uid=911,gid=911
        Volume={{ ansible_facts.env.HOME }}/Transmission/config:/config:Z
        Volume={{ ansible_facts.env.HOME }}/Transmission/downloads:/downloads:Z
      dest: "{{ ansible_facts.env.HOME }}/.config/containers/systemd/transmission.container"
    - src: /etc/hosts
      dest: /etc/hosts.orig
      mode: a-w
      force: no
      become: yes

- ansible.builtin.lineinfile:
    path: "{{ ansible_facts.env.HOME }}/.bashrc"
    regexp: ^export DOCKER_HOST=
    line: export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/podman/podman.sock

- ansible.builtin.shell:
    cmd: "{{ item.cmd | default(['curl', '--location', '--output', item.file, item.url | default(omit), '&&', 'chmod', '+x', item.file] | join(' ')) }}"
    creates: "{{ item.file }}"
  become: yes
  loop:
    - url: https://github.com/docker/compose/releases/latest/download/docker-compose-linux-x86_64
      file: /usr/local/bin/docker-compose
    - cmd: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-4 | bash
      file: /usr/local/bin/helm
    - url: https://dl.k8s.io/release/{{ lookup('ansible.builtin.url', 'https://dl.k8s.io/release/stable.txt') }}/bin/linux/amd64/kubectl
      file: /usr/local/bin/kubectl
    - url: https://github.com/kubernetes/minikube/releases/latest/download/minikube-linux-amd64
      file: /usr/local/bin/minikube

- ansible.builtin.systemd_service:
    name: podman.socket
    enabled: yes
    scope: user

- ansible.builtin.user:
    name: "{{ ansible_facts.user_id }}"
    append: yes
    groups: libvirt
  become: yes
