---

# sudo dnf -y install ansible && git log --format=%ae:%an | uniq && ansible-playbook -K main.yml

- hosts: localhost

  vars_prompt:
    - name: git_user_email
      prompt: GIT user email
      private: no
    - name: git_user_name
      prompt: GIT user name
      private: no

  tasks:
    - import_tasks: containers.yml

    - import_tasks: packages.yml

    - ansible.builtin.command:
        cmd: firewall-cmd --set-default-zone=drop
      register: command_result
      changed_when: "'ZONE_ALREADY_SET' not in command_result.stderr"

    - ansible.builtin.hostname:
        name: "{{ ansible_facts.product_version | split | first | lower }}"
        use: systemd

    - ansible.builtin.lineinfile:
        path: "{{ ansible_facts.env.HOME }}/.bashrc"
        regexp: "{{ item.regexp }}"
        line: "{{ item.line }}"
      loop:
        - regexp: ^export EDITOR=
          line: export EDITOR=/usr/bin/vim
        - regexp: ^export HISTCONTROL=
          line: export HISTCONTROL=ignoreboth

    - ansible.builtin.shell:
        cmd: curl --create-dirs --location --output {{ item.file }} {{ item.url }} && chmod +x {{ item.file }}
        creates: "{{ item.file }}"
      loop:
        - url: https://gist.githubusercontent.com/luudvig/160c757005be61102bac4e3128ab313e/raw/encrypt-symmetric.sh
          file: "{{ ansible_facts.env.HOME }}/.local/bin/encrypt-symmetric.sh"
        - url: https://gist.githubusercontent.com/luudvig/10d227c86139029e73f4fdfc763d768e/raw/two-pass.sh
          file: "{{ ansible_facts.env.HOME }}/.local/bin/two-pass.sh"
        - url: https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp
          file: "{{ ansible_facts.env.HOME }}/.local/bin/yt-dlp"

    - ansible.builtin.file:
        path: "{{ ansible_facts.env.HOME }}/.ssh"
        mode: "700"
        state: directory

    - community.crypto.openssh_keypair:
        path: "{{ ansible_facts.env.HOME }}/.ssh/id_ed25519"
        comment: "{{ ansible_facts.user_id }}@{{ ansible_facts.hostname }}"
        type: ed25519

    - community.general.dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      loop:
        - key: /org/gnome/Ptyxis/restore-session
          value: "false"
        - key: /org/gnome/Ptyxis/restore-window-size
          value: "false"
        - key: /org/gnome/desktop/calendar/show-weekdate
          value: "true"
        - key: /org/gnome/desktop/interface/clock-show-seconds
          value: "true"
        - key: /org/gnome/desktop/interface/clock-show-weekday
          value: "true"
        - key: /org/gnome/desktop/interface/color-scheme
          value: "'prefer-dark'"
        - key: /org/gnome/desktop/notifications/show-in-lock-screen
          value: "false"
        - key: /org/gnome/desktop/peripherals/touchpad/tap-to-click
          value: "false"
        - key: /org/gnome/desktop/privacy/remember-recent-files
          value: "false"
        - key: /org/gnome/desktop/session/idle-delay
          value: "uint32 900"
        - key: /org/gnome/desktop/sound/event-sounds
          value: "false"
        - key: /org/gnome/nautilus/preferences/default-folder-viewer
          value: "'list-view'"
        - key: /org/gnome/settings-daemon/plugins/color/night-light-enabled
          value: "true"
        - key: /org/gnome/settings-daemon/plugins/color/night-light-temperature
          value: "uint32 3700"
        - key: /org/gnome/settings-daemon/plugins/power/power-button-action
          value: "'interactive'"
        - key: /org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type
          value: "'nothing'"
        - key: /org/gnome/settings-daemon/plugins/power/sleep-inactive-battery-type
          value: "'nothing'"
        - key: /org/gnome/shell/favorite-apps
          value: "['org.mozilla.firefox.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Ptyxis.desktop', 'mullvad-vpn.desktop', 'google-chrome.desktop', 'chrome-faolnafnngnfdaknnbpnkhgohbobgegn-Default.desktop', 'chrome-cifhbcnohmdccbgoicgdjpfamggdegmo-Default.desktop', 'chrome-pjibgclleladliembfgfagdaldikeohf-Default.desktop']"

    - community.general.ini_file:
        path: "{{ item.path }}"
        section: "{{ item.section }}"
        option: "{{ item.option }}"
        value: "{{ item.value }}"
        create: "{{ item.create | default(omit) }}"
        no_extra_spaces: "{{ item.no_extra_spaces | default(omit) }}"
      become: "{{ item.become | default(omit) }}"
      loop:
        - path: /etc/gdm/custom.conf
          section: daemon
          option: AutomaticLoginEnable
          value: "True"
          create: no
          no_extra_spaces: yes
          become: yes
        - path: /etc/gdm/custom.conf
          section: daemon
          option: AutomaticLogin
          value: "{{ ansible_facts.user_id }}"
          create: no
          no_extra_spaces: yes
          become: yes
        - path: "{{ ansible_facts.env.HOME }}/.gitconfig"
          section: user
          option: "\temail"
          value: "{{ git_user_email }}"
        - path: "{{ ansible_facts.env.HOME }}/.gitconfig"
          section: user
          option: "\tname"
          value: "{{ git_user_name }}"
