---

# sudo dnf -y install ansible && ansible-playbook -J -K main.yml

- hosts: localhost

  tasks:
    - import_tasks: containers.yml

    - import_tasks: packages.yml

    - ansible.builtin.command:
        cmd: firewall-cmd --set-default-zone=drop
      register: command_result
      changed_when: "'ZONE_ALREADY_SET' not in command_result.stderr"

    - ansible.builtin.hostname:
        name: "{{ ansible_facts.product_version | split | first | lower }}"
        use: systemd

    - ansible.builtin.lineinfile:
        path: "{{ item.path }}"
        regexp: "{{ item.regexp | default(omit) }}"
        line: "{{ item.line }}"
        mode: "{{ item.mode | default(omit) }}"
        create: "{{ item.create | default(omit) }}"
      loop:
        - path: "{{ ansible_facts.env.HOME }}/.bashrc"
          regexp: ^export EDITOR=
          line: export EDITOR=/usr/bin/vim
        - path: "{{ ansible_facts.env.HOME }}/.bashrc"
          regexp: ^export HISTCONTROL=
          line: export HISTCONTROL=ignoreboth
        - path: "{{ ansible_facts.env.HOME }}/.git-credentials"
          line: "{{ git_credential }}"
          mode: "600"
          create: yes

    - ansible.builtin.shell:
        cmd: "{{ item.cmd | default(['curl', '--create-dirs', '--location', '--output', item.file, item.url | default(omit), '&&', 'chmod', '+x', item.file] | join(' ')) }}"
        creates: "{{ item.file }}"
      loop:
        - url: https://gist.githubusercontent.com/luudvig/160c757005be61102bac4e3128ab313e/raw/encrypt-symmetric.sh
          file: "{{ ansible_facts.env.HOME }}/.local/bin/encrypt-symmetric.sh"
        - url: https://gist.githubusercontent.com/luudvig/10d227c86139029e73f4fdfc763d768e/raw/two-pass.sh
          file: "{{ ansible_facts.env.HOME }}/.local/bin/two-pass.sh"
        - cmd: curl --location --output-dir /tmp --remote-name https://github.com/denoland/deno/releases/latest/download/deno-x86_64-unknown-linux-gnu.zip && unzip -d {{ ansible_facts.env.HOME }}/.local/bin /tmp/deno-x86_64-unknown-linux-gnu.zip deno
          file: "{{ ansible_facts.env.HOME }}/.local/bin/deno"
        - url: https://svtplay-dl.se/download/latest/svtplay-dl
          file: "{{ ansible_facts.env.HOME }}/.local/bin/svtplay-dl"
        - url: https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp
          file: "{{ ansible_facts.env.HOME }}/.local/bin/yt-dlp"

    - ansible.builtin.shell:
        cmd: "gnome-extensions info {{ item }} | grep 'Enabled: Yes' || gnome-extensions enable {{ item }}"
      register: shell_result
      changed_when: "'Enabled: Yes' not in shell_result.stdout"
      loop:
        - launch-new-instance@gnome-shell-extensions.gcampax.github.com
        - places-menu@gnome-shell-extensions.gcampax.github.com
        - window-list@gnome-shell-extensions.gcampax.github.com

    - ansible.builtin.copy:
        content: |
          [Unit]
          Description=Reset background
          ConditionKernelCommandLine=bgreset
          After=gnome-session.target

          [Service]
          ExecStart=/usr/bin/bash -c 'for k in "background picture-uri" "background picture-uri-dark" "screensaver picture-uri"; do /usr/bin/gsettings set org.gnome.desktop.$k "file:///usr/share/backgrounds/f{{ ansible_facts.distribution_major_version }}/default/f{{ ansible_facts.distribution_major_version }}.xml"; done'

          [Install]
          WantedBy=gnome-session.target
        dest: "{{ ansible_facts.env.HOME }}/.config/systemd/user/bgreset.service"

    - ansible.builtin.systemd_service:
        name: bgreset.service
        daemon_reload: yes
        enabled: yes
        scope: user

    - community.general.dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      loop:
        - key: /org/gnome/Ptyxis/restore-session
          value: "false"
        - key: /org/gnome/Ptyxis/restore-window-size
          value: "false"
        - key: /org/gnome/desktop/calendar/show-weekdate
          value: "true"
        - key: /org/gnome/desktop/interface/clock-show-seconds
          value: "true"
        - key: /org/gnome/desktop/interface/clock-show-weekday
          value: "true"
        - key: /org/gnome/desktop/interface/color-scheme
          value: "'prefer-dark'"
        - key: /org/gnome/desktop/interface/enable-hot-corners
          value: "false"
        - key: /org/gnome/desktop/interface/gtk-enable-primary-paste
          value: "true"
        - key: /org/gnome/desktop/interface/show-battery-percentage
          value: "true"
        - key: /org/gnome/desktop/notifications/show-in-lock-screen
          value: "false"
        - key: /org/gnome/desktop/peripherals/touchpad/tap-to-click
          value: "false"
        - key: /org/gnome/desktop/privacy/remember-recent-files
          value: "false"
        - key: /org/gnome/desktop/session/idle-delay
          value: "uint32 900"
        - key: /org/gnome/desktop/sound/event-sounds
          value: "false"
        - key: /org/gnome/desktop/wm/keybindings/switch-applications
          value: "['<Super>Tab']"
        - key: /org/gnome/desktop/wm/keybindings/switch-applications-backward
          value: "['<Shift><Super>Tab']"
        - key: /org/gnome/desktop/wm/keybindings/switch-windows
          value: "['<Alt>Tab']"
        - key: /org/gnome/desktop/wm/keybindings/switch-windows-backward
          value: "['<Shift><Alt>Tab']"
        - key: /org/gnome/nautilus/preferences/default-folder-viewer
          value: "'list-view'"
        - key: /org/gnome/settings-daemon/plugins/color/night-light-enabled
          value: "true"
        - key: /org/gnome/settings-daemon/plugins/color/night-light-temperature
          value: "uint32 3700"
        - key: /org/gnome/settings-daemon/plugins/power/power-button-action
          value: "'interactive'"
        - key: /org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type
          value: "'nothing'"
        - key: /org/gnome/settings-daemon/plugins/power/sleep-inactive-battery-type
          value: "'nothing'"
        - key: /org/gnome/shell/app-switcher/current-workspace-only
          value: "true"
        - key: /org/gnome/shell/favorite-apps
          value: "['org.mozilla.firefox.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Ptyxis.desktop', 'mullvad-vpn.desktop', 'com.google.Chrome.desktop', 'com.spotify.Client.desktop']"

    - community.general.ini_file:
        path: "{{ item.path }}"
        section: "{{ item.section }}"
        option: "{{ item.option }}"
        value: "{{ item.value }}"
        create: "{{ item.create | default(omit) }}"
        no_extra_spaces: "{{ item.no_extra_spaces | default(omit) }}"
      become: "{{ item.become | default(omit) }}"
      loop:
        - path: /etc/gdm/custom.conf
          section: daemon
          option: AutomaticLoginEnable
          value: "True"
          create: no
          no_extra_spaces: yes
          become: yes
        - path: /etc/gdm/custom.conf
          section: daemon
          option: AutomaticLogin
          value: "{{ ansible_facts.user_id }}"
          create: no
          no_extra_spaces: yes
          become: yes
        - path: "{{ ansible_facts.env.HOME }}/.gitconfig"
          section: credential
          option: "\thelper"
          value: "store"
        - path: "{{ ansible_facts.env.HOME }}/.gitconfig"
          section: user
          option: "\temail"
          value: "{{ git_user_email }}"
        - path: "{{ ansible_facts.env.HOME }}/.gitconfig"
          section: user
          option: "\tname"
          value: "{{ git_user_name }}"

  vars:
    git_credential: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          65643836316463366436633039613332396136326133313162633635363234643861396533343133
          3633343530633030633839643361373633336662303662370a633635633063336139373037333136
          61353264653039653835643538333761333638323437653335633366383062633632386531393266
          3234626661373034610a353930336338313735306438663664656565616163306539393965653236
          62373162643233613739643535396366656530636265363766373432393836633463373134343564
          36353364666438366132373065646134323466313364623038616335623134323865353936393538
          37663136343432386564613739373364376665346437386261313865343965626364353438366633
          36336430373835366531
    git_user_email: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35633336633835323664363561323535323065613335373231636139643362323565663838336561
          3365333438666139336230366232363536623439656533340a363864366461343938323239336466
          39653630396435393461616332393636353535353562333135393036356464383864393331316234
          3538393863363262650a646431653631343130396435306339303836373433376162656662333066
          65326266653361633937326361626238646464653262633562653439313365303932
    git_user_name: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63386164663361353635383232343335393631336664393032633964363363353766656130333631
          6564383163623133393634643433666435353333323935350a633836666361373236306464373231
          31376562653464353134343664346435646437393230353234356165363639633264643261373932
          3262616664373661350a313165363066303566613366656432626463656433333236366661393763
          3964
