---

# sudo dnf -y install ansible && ansible-playbook -J -K main.yml

- hosts: localhost

  tasks:
    - import_tasks: software.yml

    - ansible.builtin.command:
        cmd: firewall-cmd --set-default-zone=drop
      register: command_result
      changed_when: "'ZONE_ALREADY_SET' not in command_result.stderr"

    - ansible.builtin.file:
        path: "{{ ansible_facts.env.HOME }}/.config/systemd/user"
        state: directory

    - ansible.builtin.copy:
        content: "{{ item.content }}"
        dest: "{{ item.dest }}"
      loop:
        - content: |
            [Unit]
            Description=Reset background
            ConditionKernelCommandLine=bgreset
            After=gnome-session.target

            [Service]
            ExecStart=/usr/bin/bash -c 'for k in "background picture-uri" "background picture-uri-dark" "screensaver picture-uri"; do /usr/bin/gsettings set org.gnome.desktop.$k "file:///usr/share/backgrounds/f{{ ansible_facts.distribution_major_version }}/default/f{{ ansible_facts.distribution_major_version }}.xml"; done'

            [Install]
            WantedBy=gnome-session.target
          dest: "{{ ansible_facts.env.HOME }}/.config/systemd/user/bgreset.service"
        - content: |
            [Unit]
            Description=Delete xulstore

            [Service]
            ExecStart=/usr/bin/find %h/.config/mozilla/firefox -name xulstore.json -delete

            [Install]
            WantedBy=default.target
          dest: "{{ ansible_facts.env.HOME }}/.config/systemd/user/delxulstore.service"

    - ansible.builtin.hostname:
        name: "{{ ansible_facts.product_version | split | first | lower }}"
        use: systemd

    - ansible.builtin.lineinfile:
        path: "{{ item.path }}"
        regexp: "{{ item.regexp | default(omit) }}"
        line: "{{ item.line }}"
        mode: "{{ item.mode | default(omit) }}"
        create: "{{ item.create | default(omit) }}"
      loop:
        - path: "{{ ansible_facts.env.HOME }}/.bashrc"
          regexp: ^export EDITOR=
          line: export EDITOR=/usr/bin/vim
        - path: "{{ ansible_facts.env.HOME }}/.bashrc"
          regexp: ^export HISTCONTROL=
          line: export HISTCONTROL=ignoreboth
        - path: "{{ ansible_facts.env.HOME }}/.bashrc"
          regexp: ^export DOCKER_HOST=
          line: export DOCKER_HOST=unix://$XDG_RUNTIME_DIR/podman/podman.sock
        - path: "{{ ansible_facts.env.HOME }}/.bashrc"
          regexp: ^alias rclone-sync=
          line: alias rclone-sync='rclone sync remote:/ ~/Remote'
        - path: "{{ ansible_facts.env.HOME }}/.git-credentials"
          line: "{{ git_credential }}"
          mode: "600"
          create: yes

    - ansible.builtin.shell:
        cmd: "gnome-extensions info {{ item }} | grep 'Enabled: Yes' || gnome-extensions enable {{ item }}"
      register: shell_result
      changed_when: "'Enabled: Yes' not in shell_result.stdout"
      loop:
        - launch-new-instance@gnome-shell-extensions.gcampax.github.com
        - places-menu@gnome-shell-extensions.gcampax.github.com
        - window-list@gnome-shell-extensions.gcampax.github.com

    - ansible.builtin.systemd_service:
        name: "{{ item.name | default(omit) }}"
        daemon_reload: "{{ item.daemon_reload | default(omit) }}"
        enabled: "{{ item.enabled | default(omit) }}"
        scope: user
      loop:
        - daemon_reload: yes
        - name: bgreset.service
          enabled: yes
        - name: delxulstore.service
          enabled: yes
        - name: podman.socket
          enabled: yes

    - ansible.builtin.user:
        name: "{{ ansible_facts.user_id }}"
        append: yes
        groups: libvirt
      become: yes

    - community.general.dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      loop:
        - key: /org/gnome/Ptyxis/restore-session
          value: "false"
        - key: /org/gnome/Ptyxis/restore-window-size
          value: "false"
        - key: /org/gnome/desktop/calendar/show-weekdate
          value: "true"
        - key: /org/gnome/desktop/interface/clock-show-seconds
          value: "true"
        - key: /org/gnome/desktop/interface/clock-show-weekday
          value: "true"
        - key: /org/gnome/desktop/interface/color-scheme
          value: "'prefer-dark'"
        - key: /org/gnome/desktop/interface/enable-hot-corners
          value: "false"
        - key: /org/gnome/desktop/interface/gtk-enable-primary-paste
          value: "true"
        - key: /org/gnome/desktop/interface/show-battery-percentage
          value: "true"
        - key: /org/gnome/desktop/notifications/show-in-lock-screen
          value: "false"
        - key: /org/gnome/desktop/peripherals/touchpad/tap-to-click
          value: "false"
        - key: /org/gnome/desktop/privacy/remember-recent-files
          value: "false"
        - key: /org/gnome/desktop/session/idle-delay
          value: "uint32 900"
        - key: /org/gnome/desktop/sound/event-sounds
          value: "false"
        - key: /org/gnome/desktop/wm/keybindings/switch-applications
          value: "['<Super>Tab']"
        - key: /org/gnome/desktop/wm/keybindings/switch-applications-backward
          value: "['<Shift><Super>Tab']"
        - key: /org/gnome/desktop/wm/keybindings/switch-windows
          value: "['<Alt>Tab']"
        - key: /org/gnome/desktop/wm/keybindings/switch-windows-backward
          value: "['<Shift><Alt>Tab']"
        - key: /org/gnome/nautilus/preferences/default-folder-viewer
          value: "'list-view'"
        - key: /org/gnome/settings-daemon/plugins/color/night-light-enabled
          value: "true"
        - key: /org/gnome/settings-daemon/plugins/color/night-light-temperature
          value: "uint32 3700"
        - key: /org/gnome/settings-daemon/plugins/power/power-button-action
          value: "'interactive'"
        - key: /org/gnome/settings-daemon/plugins/power/sleep-inactive-ac-type
          value: "'nothing'"
        - key: /org/gnome/settings-daemon/plugins/power/sleep-inactive-battery-type
          value: "'nothing'"
        - key: /org/gnome/shell/app-switcher/current-workspace-only
          value: "true"
        - key: /org/gnome/shell/favorite-apps
          value: "['org.mozilla.firefox.desktop', 'org.gnome.Nautilus.desktop', 'org.gnome.Ptyxis.desktop', 'org.keepassxc.KeePassXC.desktop', 'mullvad-vpn.desktop']"

    - community.general.ini_file:
        path: "{{ item.path }}"
        section: "{{ item.section }}"
        option: "{{ item.option }}"
        value: "{{ item.value }}"
        create: "{{ item.create | default(omit) }}"
        no_extra_spaces: "{{ item.no_extra_spaces | default(omit) }}"
      become: "{{ item.become | default(omit) }}"
      loop:
        - path: /etc/gdm/custom.conf
          section: daemon
          option: AutomaticLoginEnable
          value: "True"
          create: no
          no_extra_spaces: yes
          become: yes
        - path: /etc/gdm/custom.conf
          section: daemon
          option: AutomaticLogin
          value: "{{ ansible_facts.user_id }}"
          create: no
          no_extra_spaces: yes
          become: yes
        - path: "{{ ansible_facts.env.HOME }}/.gitconfig"
          section: credential
          option: "\thelper"
          value: "store"
        - path: "{{ ansible_facts.env.HOME }}/.gitconfig"
          section: user
          option: "\temail"
          value: "{{ git_user_email }}"
        - path: "{{ ansible_facts.env.HOME }}/.gitconfig"
          section: user
          option: "\tname"
          value: "{{ git_user_name }}"

  vars:
    git_credential: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31353735633361633830623337396532363964623430346166353262616633323337346563656464
          6531356437383531373162363362336537303664656135620a373264323837343932303164666330
          39626238643437326336373637313236633637326232353862396461333764656331346335386137
          3766376166633766330a616664633831356432653935646230383365613664643530366338646232
          30366136663438346233323761306432306163613134626531326461333432656433393562396163
          34653866393963636239323534656165623934356634363339626436633337366334376137306231
          37653533663136336561623833353737643465653361366435643336333634376637636161623365
          63636237656562336337
    git_user_email: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          35633336633835323664363561323535323065613335373231636139643362323565663838336561
          3365333438666139336230366232363536623439656533340a363864366461343938323239336466
          39653630396435393461616332393636353535353562333135393036356464383864393331316234
          3538393863363262650a646431653631343130396435306339303836373433376162656662333066
          65326266653361633937326361626238646464653262633562653439313365303932
    git_user_name: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          63386164663361353635383232343335393631336664393032633964363363353766656130333631
          6564383163623133393634643433666435353333323935350a633836666361373236306464373231
          31376562653464353134343664346435646437393230353234356165363639633264643261373932
          3262616664373661350a313165363066303566613366656432626463656433333236366661393763
          3964
