---

- ansible.builtin.get_url:
    url: https://repository.mullvad.net/rpm/stable/mullvad.repo
    dest: /etc/yum.repos.d/mullvad.repo
  become: yes

- ansible.builtin.dnf:
    name: "{{ item.name }}"
    allowerasing: "{{ item.allowerasing | default(omit) }}"
    disable_gpg_check: "{{ item.disable_gpg_check | default(omit) }}"
  become: yes
  loop:
    - name: https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_facts.distribution_major_version }}.noarch.rpm
      disable_gpg_check: yes
    - name: ffmpeg
      allowerasing: yes
    - name: mullvad-vpn
    - name: vim-enhanced

- community.general.flatpak_remote:
    name: flathub
  become: yes

- community.general.flatpak:
    name: "{{ item.name }}"
  loop:
    - name: org.gimp.GIMP
    - name: org.keepassxc.KeePassXC
    - name: org.videolan.VLC

- community.general.ini_file:
    path: /etc/fwupd/remotes.d/lvfs.conf
    section: fwupd Remote
    option: Enabled
    value: "false"
    create: no
    no_extra_spaces: yes
  become: yes
